# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [14]:
arr2 = np.zeros(10)
print(arr2)


3. Create a vector with values ranging from 10 to 49

In [16]:
arr3 = np.arange(10,50)
print(arr3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [17]:
arr3.shape

(40,)

5. Print the type of the previous array in question 3

In [18]:
arr3.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [22]:
print(np.version.version)
#print(np.show_config())

1.18.5


7. Print the dimension of the array in question 3


In [23]:
arr3.ndim

1

8. Create a boolean array with all the True values

In [26]:
arrBool = np.array([True, True, True], dtype = bool)
print(arrBool)

[ True  True  True]


dtype('bool')

9. Create a two dimensional array




In [27]:
arr2d9 = np.array([[1,2,3], [4,5,6]])
#print(arr2d9)
#arr2d9.ndim

[[1 2 3]
 [4 5 6]]


2

10. Create a three dimensional array



In [28]:
arr3d10 = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
#arr3d10.ndim

3

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [52]:
arr11 = np.arange(10)
print(arr11)
#arr11R = np.flip(arr11)
arr11R = arr11[::-1]
print(arr11R)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [54]:
arr12 = np.zeros(10)
arr12[5] = 1
print(arr12)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [57]:
arr13 = np.identity(3)
print(arr13)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [64]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.astype(float))

[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [65]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
print(arr1*arr2)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [67]:
arrC = arr1 == arr2
print(arrC)

[[False False False]
 [False False False]]


array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [69]:
arr = np.arange(10)
arrOdd = arr[1::2]
print(arrOdd)

[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [78]:
arr[1::2] = -1
arrNew = arr
print(arrNew)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [83]:
arr[5:9] = 12
print(arr)

[ 0 -1  2 -1  4 12 12 12 12 -1]


20. Create a 2d array with 1 on the border and 0 inside

In [100]:
arr2d = np.zeros([5, 5])
arr2d[0:5:4 ,0:5:4]= 1
print(arr2d)

[[1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [102]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

arr2d[1,1] = 12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [107]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0,:] = 64
print(arr3d)

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [111]:
arr1d = np.arange(10)
arr2d = arr1d.reshape(2,5)
print(arr2d)
arrSliced = arr2d[0,:]
print(arrSliced)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [112]:
arr1d = np.arange(10)
arr2d = arr1d.reshape(2,5)
print(arr2d)
var = arr2d[1,1]
print(var)

[[0 1 2 3 4]
 [5 6 7 8 9]]
6


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [114]:
arr1d = np.arange(15)
arr2d = arr1d.reshape(3,5)
print(arr2d)
arrSliced = arr2d[0:2, 2]
print(arrSliced)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[2 7]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [127]:
arr = np.random.rand(10,10)*10
#print(arr)
minN = np.min(arr)
maxN = np.max(arr)
print(minN)
print(maxN)

0.07273909137083034
9.99190239893417


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [129]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
common = np.intersect1d(a,b)
print(common)

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [130]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.where(a==b)
print(c)

(array([1, 3, 5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [139]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
#print(names)
print(data)
print("                              ")
print("                              ")
print(data[names != 'Will'])

[[-0.84683531 -0.17627566  1.5430052   0.42685999]
 [ 0.78742849 -0.97417961 -0.23739472 -0.67854787]
 [-0.90777881  1.37945849  0.13483853  0.83809063]
 [ 0.04670877  0.60784133 -0.26514171  0.40507187]
 [ 0.68417872  0.69325696  0.45969707  1.0683792 ]
 [ 2.15785093  0.48500129 -0.19478557  1.86494404]
 [ 0.06286731 -1.77183156 -0.81943062 -0.75325124]]
                              
                              
[[-0.84683531 -0.17627566  1.5430052   0.42685999]
 [ 0.78742849 -0.97417961 -0.23739472 -0.67854787]
 [ 0.04670877  0.60784133 -0.26514171  0.40507187]
 [ 2.15785093  0.48500129 -0.19478557  1.86494404]
 [ 0.06286731 -1.77183156 -0.81943062 -0.75325124]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [141]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
#print(names)
print(data)
print("                              ")
print("                              ")
print(data[(names != 'Will') & (names != 'Joe')])

[[-0.90863213 -0.18604125  0.94723663 -0.49534364]
 [-0.53977513  2.25893487 -1.08573189  1.05674937]
 [-0.13381657  0.34800144  1.99958647 -0.95161751]
 [ 0.12330754 -0.70837272  0.24498188 -1.29879645]
 [-0.02937015  1.63144006 -0.43446056 -0.66279728]
 [ 0.09081136  1.29937335 -0.59845575  0.29681138]
 [-1.12199452  1.20873451 -0.95633216 -0.93505936]]
                              
                              
[[-0.90863213 -0.18604125  0.94723663 -0.49534364]
 [ 0.12330754 -0.70837272  0.24498188 -1.29879645]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [167]:
arr = np.arange(1,16)*1.002
arr = arr.reshape(5,3)
print(arr)


[[ 1.002  2.004  3.006]
 [ 4.008  5.01   6.012]
 [ 7.014  8.016  9.018]
 [10.02  11.022 12.024]
 [13.026 14.028 15.03 ]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [170]:
arr = np.arange(1,17)*1.002
arr = arr.reshape(2,2,4)
print(arr)

[[[ 1.002  2.004  3.006  4.008]
  [ 5.01   6.012  7.014  8.016]]

 [[ 9.018 10.02  11.022 12.024]
  [13.026 14.028 15.03  16.032]]]


33. Swap axes of the array you created in Question 32

In [171]:
arrS = np.transpose(arr)
print(arrS)

[[[ 1.002  9.018]
  [ 5.01  13.026]]

 [[ 2.004 10.02 ]
  [ 6.012 14.028]]

 [[ 3.006 11.022]
  [ 7.014 15.03 ]]

 [[ 4.008 12.024]
  [ 8.016 16.032]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [179]:
arr = np.arange(10)
print(arr)
print("         ")
arrSR = np.sqrt(arr)
print(arrSR)
arrSR[arrSR < 0.5] = 0
print ("                   ")
print(arrSR)

[0 1 2 3 4 5 6 7 8 9]
         
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
                   
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [204]:
arr1 = np.random.randn(12)
arr2 = np.random.randn(12)
print(arr1)
print("         ")
print(arr2)

arrMax = np.where(arr1>arr2, arr1, arr2)
print("        ")
print(arrMax)

[-1.24536744  0.9319423   0.2563222   1.47033686  0.8332085   1.12092665
  0.48787216  1.23922637  0.61597456  0.02818171  1.43534568  0.7045351 ]
         
[-0.65306566  0.11537442  1.10235402 -0.58778344 -0.38718925  0.28499339
  0.81481236 -0.09278557  2.79772712 -0.06838381  0.54845684 -0.07250976]
        
[-0.65306566  0.9319423   1.10235402  1.47033686  0.8332085   1.12092665
  0.81481236  1.23922637  2.79772712  0.02818171  1.43534568  0.7045351 ]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
---
Find the unique names and sort them out!


In [205]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
namesU = np.unique(names)
print(namesU)

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [220]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
check = np.invert(np.isin(a,b))
print(a[check])


[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [235]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
print("            ")

newColumn = np.array([[10,10,10]])

sampleArray = np.delete(sampleArray,1,1)
print(sampleArray)

finalArray = np.insert(sampleArray, 1, newColumn, 1)
print("         ")
print(finalArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
            
[[34 73]
 [82 12]
 [53 66]]
         
[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [237]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z = np.dot(x,y)
print(z)

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [243]:
a = np.random.randn(4,5)
print(a)
print("           ")
sum = np.cumsum(a)
print(sum)

[[ 0.55031339 -1.03311046 -0.51557808 -3.18213468  0.42600681]
 [ 0.8798189   0.26826955 -0.14367128 -0.12998011  0.27084526]
 [-0.16172298  1.13865622 -1.15829756 -1.90357096 -0.29077438]
 [ 0.5973224  -0.06380735 -1.1602329  -0.35130481  1.61792797]]
           
[ 0.55031339 -0.48279707 -0.99837515 -4.18050983 -3.75450302 -2.87468412
 -2.60641457 -2.75008585 -2.88006596 -2.6092207  -2.77094368 -1.63228746
 -2.79058502 -4.69415598 -4.98493036 -4.38760796 -4.45141531 -5.61164821
 -5.96295301 -4.34502504]
